# Generated by Django 4.0.1 on 2022-01-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(decimal_places=3, max_digits=3)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=3)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date', models.DateField()),
            ],
        ),
    ]
