# Generated by Django 4.0.1 on 2022-01-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='port',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='port',
            name='temperature',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
