# Generated by Django 4.0.1 on 2022-01-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_alter_port_latitude_alter_port_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='temperature',
            field=models.IntegerField(max_length=3),
        ),
    ]
