# Generated by Django 4.0.1 on 2022-01-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_alter_port_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
