# Generated by Django 4.0.1 on 2022-02-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0004_alter_port_date_alter_port_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_import_csv', models.FileField(upload_to='ports')),
            ],
        ),
    ]
